Set ws = CreateObject("Wscript.Shell") 
Msgbox "..." , 0 , "毫无意义的弹窗I"
Msgbox ".." , 0 , "毫无意义的弹窗II"
Msgbox "." , 0 , "毫无意义的弹窗III"
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k CPU压力测试工具TGT",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
ws.run "cmd /k",vbhide
